.TH MPD_SEND_PASSWORD 3 2019
.SH NAME
mpd_send_password, mpd_run_password \- password authentication for MPD
.SH SYNOPSIS
.B #include <mpd/client.h>
.PP
.BI "bool mpd_send_password(struct mpd_connection *" connection ","
.BI "const char *" password );
.PP
.BI "bool mpd_run_password(struct mpd_connection *" connection ","
.BI "const char *" password );
.SH DESCRIPTION
The
.BR mpd_send_password ()
function sends the 
.I password 
to MPD to gain more privileges. The function receives a
.I connection
to the MPD server and a
.I password
string.
.PP
The
.BR mpd_run_password ()
function is a shortcut for
.BR mpd_send_password ()
and
.BR mpd_response_finish (3).
.SH RETURN VALUE
.BR mpd_send_password ()
and
.BR mpd_run_password ()
return true on success, or false otherwise.
.SH ERRORS
The user should use one of the error functions of libmpdclient for
error-checking.
.SH SEE ALSO
.BR mpd_response_finish (3),
.BR mpd_connection_get_error (3),
.BR mpd_connection_get_error_message (3),
.BR mpd_connection_get_server_error (3),
.BR mpd_connection_get_system_error (3)
