.TH MPD_SEARCH_DB_SONGS 3 2019
.SH NAME
mpd_search_db_songs, mpd_search_add_db_songs,
mpd_search_add_db_songs_to_playlist, mpd_search_queue_songs, mpd_search_db_tags
\- initiate a search operation on the MPD server
.SH SYNOPSIS
.B #include <mpd/client.h>
.PP
.BI "bool mpd_search_db_songs(struct mpd_connection *" connection ","
.BI "bool " exact );
.PP
.BI "bool mpd_search_add_db_songs(struct mpd_connection *" connection ","
.BI "bool " exact );
.PP
.BI "bool mpd_search_add_db_songs_to_playlist(struct "
.BI "mpd_connection *" connection ", const char *" playlist_name );
.PP
.BI "bool mpd_search_queue_songs(struct mpd_connection *" connection ","
.BI "bool " exact );
.PP
.BI "bool mpd_search_db_tags(struct mpd_connection *" connection ","
.BI "enum mpd_tag_type " type );
.SH DESCRIPTION
The
.BR mpd_search_db_songs ()
function searches for songs in the database.
.I exact
makes the search case-sensitive. Constraints may be specified with, e.g.,
.BR mpd_search_add_tag_constraint (3).
Send the search command with
.BR mpd_search_commit (3),
and read the response items with
.BR mpd_recv_song (3).
The function also receives a
.I connection
to the MPD server.
.PP
The
.BR mpd_search_add_db_songs ()
function searches for songs in the database and adds the result to the queue.
.I exact
makes the search case-sensitive. Constraints may be specified with, e.g.,
.BR mpd_search_add_tag_constraint (3).
Send the search command with
.BR mpd_search_commit (3),
and read the response items with
.BR mpd_recv_song (3).
The function also receives a
.I connection
to the MPD server.
.PP
The
.BR mpd_search_add_db_songs_to_playlist ()
function searches for songs in the database and adds the result to the playlist
.IR playlist_name . 
Constraints may be specified with, e.g.,
.BR mpd_search_add_tag_constraint (3).
Send the search command with
.BR mpd_search_commit (3),
and read the response items with
.BR mpd_recv_song (3).
The function also receives a
.I connection
to the MPD server.
.PP
The
.BR mpd_search_queue_songs ()
function search for songs in the queue.
Constraints may be specified with, e.g.,
.BR mpd_search_add_tag_constraint (3).
Send the search command with
.BR mpd_search_commit (3),
and read the response items with
.BR mpd_recv_song (3).
The function also receives a
.I connection
to the MPD server.
.PP
The
.BR mpd_search_db_tags ()
function obtains a list of unique tag values for
.I type
from the database. Constraints may be specified with, e.g.,
.BR mpd_search_add_tag_constraint (3).
Send the search command with
.BR mpd_search_commit (3),
and read the response items with
.BR mpd_recv_pair_tag (3).
The function also receives a
.I connection
to the MPD server.
.SS The mpd_tag_type enum
The
.I mpd_tag_type
enum is defined as follows:
.PP
.in +4n
.EX
/**
 * @since libmpdclient 2.10 added support for #MPD_TAG_MUSICBRAINZ_RELEASETRACKID.
 * @since libmpdclient 2.11 added support for #MPD_TAG_ARTIST_SORT and #MPD_TAG_ALBUM_ARTIST_SORT
 * @since libmpdclient 2.17 added support for #MPD_TAG_LABEL and #MPD_TAG_MUSICBRAINZ_WORKID.
 */
enum mpd_tag_type
{
	/**
	 * Special value returned by mpd_tag_name_parse() when an
	 * unknown name was passed.
	 */
	MPD_TAG_UNKNOWN = -1,

	MPD_TAG_ARTIST,
	MPD_TAG_ALBUM,
	MPD_TAG_ALBUM_ARTIST,
	MPD_TAG_TITLE,
	MPD_TAG_TRACK,
	MPD_TAG_NAME,
	MPD_TAG_GENRE,
	MPD_TAG_DATE,
	MPD_TAG_COMPOSER,
	MPD_TAG_PERFORMER,
	MPD_TAG_COMMENT,
	MPD_TAG_DISC,

	MPD_TAG_MUSICBRAINZ_ARTISTID,
	MPD_TAG_MUSICBRAINZ_ALBUMID,
	MPD_TAG_MUSICBRAINZ_ALBUMARTISTID,
	MPD_TAG_MUSICBRAINZ_TRACKID,
	MPD_TAG_MUSICBRAINZ_RELEASETRACKID,

	MPD_TAG_ORIGINAL_DATE,

	MPD_TAG_ARTIST_SORT,
	MPD_TAG_ALBUM_ARTIST_SORT,

	MPD_TAG_ALBUM_SORT,
	MPD_TAG_LABEL,
	MPD_TAG_MUSICBRAINZ_WORKID,

	MPD_TAG_GROUPING,
	MPD_TAG_WORK,
	MPD_TAG_CONDUCTOR,

	/* IMPORTANT: the ordering of tag types above must be
	   retained, or else the libmpdclient ABI breaks */

	MPD_TAG_COUNT
};
.EE
.in

.SH RETURN VALUE
All functions return true on success, false on error.
.SH ERRORS
The user should use one of the error functions of libmpdclient for
error-checking.
.SH HISTORY
The
.BR mpd_search_add_db_songs_to_playlist ()
function was added to libmpdclient 2.17.
.PP
The use of
.I exact
for case-insensitive operations on
.BR mpd_search_add_db_songs ()
was added to MPD 0.16.
.SH SEE ALSO
.BR mpd_recv_song (3),
.BR mpd_recv_pair_tag (3),
.BR mpd_search_add_base_constraint (3),
.BR mpd_search_add_uri_constraint (3),
.BR mpd_search_add_tag_constraint (3),
.BR mpd_search_add_any_tag_constraint (3),
.BR mpd_search_add_modified_since_constraint (3),
.BR mpd_search_add_expression (3),
.BR mpd_search_add_group_tag (3),
.BR mpd_search_add_sort_name (3),
.BR mpd_search_add_sort_tag (3),
.BR mpd_search_add_window (3),
.BR mpd_count_db_songs (3),
.BR mpd_search_commit (3),
.BR mpd_search_cancel (3),
.BR mpd_recv_pair_tag (3),
.BR mpd_connection_get_error (3),
.BR mpd_connection_get_error_message (3),
.BR mpd_connection_get_server_error (3),
.BR mpd_connection_get_system_error (3)
